#declare and initialise scoreboards and settings
scoreboard objectives add gm4_tnt_data dummy
scoreboard objectives add gm4_entity_version dummy

#generated by generator   V
execute unless score tnt_landmines gm4_modules matches 1 run data modify storage gm4:log queue append value {type:"install",module:"TNT Landmines"}
execute unless score tnt_landmines gm4_earliest_version < tnt_landmines gm4_modules run scoreboard players operation tnt_landmines gm4_earliest_version = tnt_landmines gm4_modules
scoreboard players set tnt_landmines gm4_modules 1

schedule function gm4_tnt_landmines:main 10t
schedule function gm4_tnt_landmines:tick 1t

#$moduleUpdateList
