# checks each slot for item tags
# @s = crafter armor stand
# located at the center of the block
# run from gm4_custom_crafters:process_input/check_item via #gm4_custom_crafter:custom_item_checks

# generated by generate_item_tags.py
