import json
import urllib.request
import itertools
import pathlib
print("Generating disassembly loot tables...")

MCVERSION = "1.19.2"

diamond_items = ["minecraft:diamond_sword","minecraft:diamond_pickaxe","minecraft:diamond_axe","minecraft:diamond_shovel","minecraft:diamond_hoe","minecraft:diamond_helmet","minecraft:diamond_chestplate","minecraft:diamond_leggings","minecraft:diamond_boots"]
diamond_durability = [1562, 1562, 1562, 1562, 1562, 364, 529, 496, 430]
iron_items = ["minecraft:iron_sword","minecraft:iron_pickaxe","minecraft:iron_axe","minecraft:iron_shovel","minecraft:iron_hoe","minecraft:iron_helmet","minecraft:iron_chestplate","minecraft:iron_leggings","minecraft:iron_boots"]
iron_durability = [251, 251, 251, 251, 251, 166, 241, 226, 196]
gold_items = ["minecraft:golden_sword","minecraft:golden_pickaxe","minecraft:golden_axe","minecraft:golden_shovel","minecraft:golden_hoe","minecraft:golden_helmet","minecraft:golden_chestplate","minecraft:golden_leggings","minecraft:golden_boots"]
gold_durability = [33, 33, 33, 33, 33, 78, 113, 106, 92]
leather_items = ["minecraft:leather_helmet","minecraft:leather_chestplate","minecraft:leather_leggings","minecraft:leather_boots"]
leather_durability = [56, 81, 76, 66]
other_items = ["minecraft:turtle_helmet","minecraft:bow","minecraft:crossbow","minecraft:shears","minecraft:fishing_rod","minecraft:flint_and_steel"]
other_durability = [276, 385, 466, 239, 65, 65]
normal_items = diamond_items + iron_items + gold_items + leather_items + other_items
normal_durability = diamond_durability + iron_durability + gold_durability + leather_durability + other_durability
special_items = ["minecraft:shield"]
special_durability = [337]

recipes_url = f"https://raw.githubusercontent.com/misode/mcmeta/{MCVERSION}-summary/data/recipe/data.min.json"
recipes = json.load(urllib.request.urlopen(recipes_url))

pairs = {}

for i, item in enumerate(normal_items):
  recipe = recipes[item.split(":")[1]]
  if recipe["type"] == "minecraft:crafting_shaped":
    pattern = ''
    for row in recipe["pattern"]:
      if len(row) < 2: row = " " + row
      if len(row) < 3: row = row + " "
      pattern = pattern + row
    while (len(pattern) < 9):
      pattern = pattern + " "
    pattern = ["".join(g) for k, g in itertools.groupby(pattern)]
    pattern = [item for sublist in pattern for item in sublist]
    recipe["key"][" "] = {"item": "minecraft:air"}
    pattern = [(recipe["key"][p[0]]["item"], len(p)) for p in pattern]
  else:
    pattern = []
    for ingredient in recipe["ingredients"]:
      pattern.append((ingredient["item"], 1))
    if len(pattern) < 9:
      pattern.append(("minecraft:air", 9-len(pattern)))

  pools = []
  for p in pattern:
    base = {"rolls": p[1], "entries": [{"type": "minecraft:item", "name": p[0]}]}
    if p[0] == "minecraft:air":
      pools.append(base)
      continue
    base["entries"][0]["conditions"] = [{
      "condition":"value_check",
      "value":{
        "type":"score",
        "target":{
          "type":"fixed",
          "name":"$damage"
        },
        "score":"gm4_disassembler"
      },
      "range":{
        "min":0,
        "max":{
          "type":"uniform",
          "min":0,
          "max":normal_durability[i]
        }
      }
    }]
    pools.append({"rolls": p[1], "entries": [{"type": "minecraft:alternatives", "children": [base["entries"][0],{"type": "minecraft:item", "name": "minecraft:air"}]}]})
  
  lootTable = {
    "__comment":"Generated by generate_disassembly.py",
    "type": "minecraft:generic",
    "pools": pools
  }

  with open("gm4_disassemblers/data/gm4_disassemblers/loot_tables/disassembleables/"+item.split(":")[1]+".json", "w+") as file:
    json.dump(lootTable, file, indent=2)

caller = {"__comment":"Generated by generate_disassembly.py", "type": "minecraft:fishing","pools":[{"rolls":1,"entries":[{"type":"minecraft:alternatives","children":[]}]}]}  
for item in normal_items:
  caller["pools"][0]["entries"][0]["children"].append(
    {
      "type": "minecraft:loot_table",
      "name": f'gm4_disassemblers:disassembleables/{item.split(":")[1]}',
      "conditions":[{
        "condition":"match_tool",
            "predicate": {
                  "items": [item]
            }
      }]
    }
  )
  if item in diamond_items:
    caller["pools"][0]["entries"][0]["children"][-1]["conditions"].append({"condition":"value_check","range":1,"value":{"type":"score","target":{"type":"fixed","name":"disassemble_diamonds"},"score":"gm4_disassembler"}})
with open("gm4_disassemblers/data/gm4_disassemblers/loot_tables/caller.json", "w+") as file:
  json.dump(caller, file, indent=2)
print("Done!")
