# create storage to hold the trade data for furniture items in furniture station
# @s = unspecified
# at unspecified
# run from init
# this function was generated by generate.py

{{ trades_init }}

{{ trades_list }}

{{ trades_append }}
data remove storage gm4_furniture:temp new_trades
