from beet import Context, Advancement, Function

def beet_default(ctx: Context):
    for bit in range(16):
        for value in range(2):
            ctx.data[f"gm4_hooked_entity:fished/bit_{bit}_{value}"] = Advancement({
                "criteria":{
                    "fishing_rod_hooked":{
                        "trigger":"minecraft:fishing_rod_hooked",
                        "conditions":{
                            "entity": [
                                {
                                    "condition": "minecraft:entity_scores",
                                    "entity": "this",
                                    "scores": {
                                        f"gm4_hooked_entity.id_bit.{bit}": value
                                    }
                                }
                            ]
                        }
                    }
                },
                "rewards":{
                    "function": f"gm4_hooked_entity:player/bit_{bit}_{value}"
                }
            })
            ctx.data[f"gm4_hooked_entity:player/bit_{bit}_{value}"] = Function([
                f"# player adv logic for getting bit {bit} at value {value}. Generated by generate_files.py.",
                f"# run from advancement fished/bit_{bit}_{value}\n",
                f"advancement revoke @s only gm4_hooked_entity:fished/bit_{bit}_{value}\n",
                "execute if entity @s[gamemode=adventure] run return fail\n",
                "data modify storage gm4_hooked_entity:temp bit_data set value {bit_score:\"" + f"gm4_hooked_entity.id_bit.{bit}={value}\", bit:\"{bit}\"" + "}",
                "data modify storage gm4_hooked_entity:temp bit_data.UUID set from entity @s UUID",
                "function gm4_hooked_entity:player/received_bit with storage gm4_hooked_entity:temp bit_data"
            ])
