name: Build modules

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
  workflow_dispatch:

env:
  VERSION: '26.2'
  COMMIT_MSG: ${{ github.event.head_commit.message }}

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.event_name != 'pull_request' && 'release' || format('pr-{0}', github.event.number) }}
    steps:
      - uses: actions/checkout@v7

      - name: Checkout release branch
        uses: actions/checkout@v7
        with:
          ref: release
          path: release

      - name: Fetch pull request base
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Build and publish all modules
        if: github.event_name != 'pull_request'
        run: uv run beet -p beet-release.yaml -l ${{ env.LOG_LEVEL }} build
        env:
          BEET_MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          BEET_SMITHED_TOKEN: ${{ secrets.SMITHED_TOKEN }}
          LOG_LEVEL: ${{ runner.debug == 1 && 'DEBUG' || 'INFO'}}
          MASTER_BUILD: true

      - name: Build all modules for pull request
        if: github.event_name == 'pull_request'
        run: uv run beet -p beet-release.yaml -l ${{ env.LOG_LEVEL }} build
        env:
          LOG_LEVEL: ${{ runner.debug == 1 && 'DEBUG' || 'INFO'}}

      - name: Remove non-modules for artifact
        if: github.event_name == 'pull_request'
        run: |
          rm -r release/$VERSION/generated
          rm release/$VERSION/lib_*
          rm release/$VERSION/meta.json

      - name: Retrieve commit sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Upload zip artifact
        uses: actions/upload-artifact@v7
        with:
          name: "${{ format('Modules for {0} #{1}', \
            case(github.event_name != 'pull_request', 'publish', 'pull request'),\
            case(github.event_name != 'pull_request', env.SHORT_SHA, github.event.number)) }}"
          path: ${{ github.workspace }}/release/${{ env.VERSION }}/

      - name: Commit release
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.email "${{ github.event.head_commit.author.email }}"
          git config --global user.name "${{ github.event.head_commit.author.username }}"
          cd release
          git add .
          git commit -m "🚀 ${{ github.event.after }} $COMMIT_MSG"

      - name: Push release
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: release
          branch: release

      - name: Upload .beet_cache as artifact
        uses: actions/upload-artifact@v7
        with:
          name: .beet_cache
          path: ${{ github.workspace }}/.beet_cache/
          include-hidden-files: true
          retention-days: 2

      - name: Rename log file
        run: mv ${{ github.workspace }}/logs/summary_logs.pkl ${{ github.workspace }}/logs/build_log.pkl

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/logs/build_log.pkl
          archive: false
          retention-days: 2

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://fabricmc.net/use/server/
          # https://modrinth.com/mod/fabric-api/versions
          # https://modrinth.com/mod/packtest/versions
          - version: '26.2'
            fabric_server_url: https://meta.fabricmc.net/v2/versions/loader/26.2-rc-2/0.19.3/1.1.1/server/jar
            fabric_api_url: https://cdn.modrinth.com/data/P7dR8mSH/versions/Fsy077WD/fabric-api-0.152.0%2B26.2.jar
            packtest_url: https://cdn.modrinth.com/data/XsKUhp45/versions/qT2wdJhc/packtest-2.6.0-beta1.jar
            command_limit_tracer_url: https://cdn.modrinth.com/data/Ao12dSbt/versions/zKvlVzlN/commandlimittracer-0.3.0.jar
    name: 'test-${{ matrix.version }}'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Build all modules for tests
        run: uv run beet -p beet-test.yaml -l ${{ env.LOG_LEVEL }} build
        env:
          LOG_LEVEL: ${{ runner.debug == 1 && 'DEBUG' || 'INFO'}}

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Download server files
        run: |
          curl -o server.jar ${{ matrix.fabric_server_url }}
          mkdir mods
          curl -o mods/fabric-api.jar ${{ matrix.fabric_api_url }}
          curl -o mods/packtest.jar ${{ matrix.packtest_url }}
          curl -o mods/command_limit_tracer.jar ${{ matrix.command_limit_tracer_url }}

      - name: Copy packs to world
        run: |
          mkdir -p world/datapacks
          rm out/gm4_zauber_liquids.zip
          cp out/gm4_*.zip world/datapacks

      - name: Run test server
        id: run-tests
        run: |
          java -Xmx2G -Dpacktest.auto -Dpacktest.auto.annotations -jar server.jar nogui

      - name: Upload test world
        if: ${{ failure() && steps.run-tests.conclusion == 'failure' }}
        uses: actions/upload-artifact@v7
        with:
          name: 'Test world in ${{ matrix.version }} for ${{ github.sha }}'
          path: ${{ github.workspace }}/world/

  publish:
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
    needs: build
    strategy:
      matrix:
        platform: [modrinth, smithed]
    # concurrency:
    #   group: release
    name: 'publish-${{ matrix.platform }}'
    steps:
      - uses: actions/checkout@v7

      - name: Retrieve commit sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Download module zips from artifact
        uses: actions/download-artifact@v7
        with:
          name: 'Modules for publish #${{ env.SHORT_SHA }}'
          path: ${{ github.workspace }}/release/${{ env.VERSION }}/

      - name: Restore .beet_cache from artifact
        uses: actions/download-artifact@v7
        with:
          name: .beet_cache
          path: ${{ github.workspace }}/.beet_cache

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Publish all modules
        run: uv run beet -p beet-publish.yaml -l ${{ env.LOG_LEVEL }} -s meta.gm4.publish_to=${{ matrix.platform }} build
        env:
          BEET_MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          BEET_SMITHED_TOKEN: ${{ secrets.SMITHED_TOKEN }}
          LOG_LEVEL: ${{ runner.debug == 1 && 'DEBUG' || 'INFO'}}

      - name: Rename log file
        run: mv ${{ github.workspace }}/logs/summary_logs.pkl ${{ github.workspace }}/logs/publish_${{ matrix.platform }}_log.pkl

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/logs/publish_${{ matrix.platform }}_log.pkl
          archive: false
          retention-days: 2

  summarize:
    runs-on: ubuntu-24.04
    needs: [build, publish]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v7

      - name: Restore .beet_cache from artifact
        uses: actions/download-artifact@v7
        with:
          name: .beet_cache
          path: ${{ github.workspace }}/.beet_cache

      - name: Restore log files from artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: '*_log.pkl'
          path: ${{ github.workspace }}/logs
          merge-multiple: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Summarize build logs
        run: uv run beet -p beet-summarize.yaml -s meta.gm4.summarize_type=${{ github.event_name != 'pull_request' && 'release' || 'pull_request' }} build
